USE krautundrueben;


CREATE TABLE SAMMLUNGSTYP (
    SAMMLUNGSTYPNR        INTEGER NOT NULL AUTO_INCREMENT,
    TYPBEZEICHNUNG        VARCHAR(50),
    PRIMARY KEY (SAMMLUNGSTYPNR)
);

CREATE TABLE SAMMLUNG (
    SAMMLUNGSNR   INTEGER NOT NULL AUTO_INCREMENT,
    SAMMLUNGSBEZEICHNUNG VARCHAR(50),
    RABATT			INTEGER,
    SAMMLUNGSTYPNR			INTEGER,
    PRIMARY KEY (SAMMLUNGSNR),
    FOREIGN KEY (SAMMLUNGSTYPNR) REFERENCES SAMMLUNGSTYP (SAMMLUNGSTYPNR)
);

CREATE TABLE BESTELLUNGSAMMLUNG (
    BESTELLNR       INTEGER NOT NULL,
    SAMMLUNGSNR       INTEGER NOT NULL,
    MENGE     		INTEGER,
    PRIMARY KEY (BESTELLNR,SAMMLUNGSNR),
    FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR),
    FOREIGN KEY (SAMMLUNGSNR) REFERENCES SAMMLUNG (SAMMLUNGSNR)
);

CREATE TABLE SAMMLUNGZUTAT (
    ZUTATENNR       INTEGER NOT NULL,
    SAMMLUNGSNR       INTEGER NOT NULL,
    ZUTATENMENGE     		INTEGER,
    PRIMARY KEY (ZUTATENNR,SAMMLUNGSNR),
    FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR),
    FOREIGN KEY (SAMMLUNGSNR) REFERENCES SAMMLUNG (SAMMLUNGSNR)
);

CREATE TABLE ALLERGEN (
    ALLERGENNR        INTEGER NOT NULL AUTO_INCREMENT,
    ALLERGENBEZEICHNUNG        VARCHAR(50),
    PRIMARY KEY (ALLERGENNR)
);

CREATE TABLE ERNAEHRUNGSKATEGORIE (
    KATEGORIENR        INTEGER NOT NULL AUTO_INCREMENT,
    KATEGORIEBEZEICHNUNG        VARCHAR(50),
    PRIMARY KEY (KATEGORIENR)
);

CREATE TABLE ZUTATALLERGEN (
    ZUTATENNR       INTEGER NOT NULL,
    ALLERGENNR       INTEGER NOT NULL,
    PRIMARY KEY (ZUTATENNR,ALLERGENNR),
    FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR),
    FOREIGN KEY (ALLERGENNR) REFERENCES ALLERGEN (ALLERGENNR)
);

CREATE TABLE ZUTATKATEGORIE (
    ZUTATENNR       INTEGER NOT NULL,
    KATEGORIENR       INTEGER NOT NULL,
    PRIMARY KEY (ZUTATENNR,KATEGORIENR),
    FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR),
    FOREIGN KEY (KATEGORIENR) REFERENCES ERNAEHRUNGSKATEGORIE (KATEGORIENR)
);