<div class="main-container"%>
    <h2 class="main-title">Willkommen bei "Kraut & Rüben" – Ihrem regionalen Paradies für frisches Obst und Gemüse!</h2>
    <p class="main-paragraph">Inmitten der idyllischen Landschaft, umgeben von saftig grünen Feldern und duftenden Obstgärten, finden Sie unseren liebevoll geführten Betrieb. Wir sind stolz darauf, Ihnen nur das Beste aus der Natur anzubieten – von knackigen Äpfeln bis hin zu saftigen Birnen und allem dazwischen.</p>
    <p class="main-paragraph">Unser Herz schlägt für die Verbindung zur Natur und zu unserer Gemeinschaft. Als regionaler Betrieb sind wir fest mit unserer Umgebung verwurzelt und setzen uns dafür ein, dass jeder Bissen, den Sie bei uns genießen, reich an Geschmack und Qualität ist. Wir legen großen Wert auf nachhaltige Anbaumethoden, um die Umwelt zu schonen und unsere köstlichen Erzeugnisse auf Ihrem Teller zu einem wahren Genuss werden zu lassen.</p>
    <p class="main-paragraph">Auf unserem Feld mit den Apfelkisten gedeiht eine Fülle von Sorten – von den süßesten Gala-Äpfeln bis hin zu den säuerlich erfrischenden Granny Smiths. Jeder Apfel wird von Hand gepflückt und sorgfältig ausgewählt, um sicherzustellen, dass nur die frischesten und geschmackvollsten Früchte den Weg zu Ihnen finden.</p>

    <img src="/images/ho1.png" class="main-image">
    <p class="main-paragraph">Und schauen Sie sich nur unseren leidenschaftlichen Bauern an, der voller Hingabe Birnen pflückt! Diese köstlichen Früchte werden von unseren Bäumen mit Liebe und Sorgfalt geerntet, um Ihnen den unvergleichlichen Genuss eines saftigen Bisses zu bieten. Unsere Birnen sind so reif und saftig, dass Ihr Gaumen vor Freude tanzen wird.</p>
    <p class="main-paragraph">Doch unser Sortiment beschränkt sich nicht nur auf Äpfel und Birnen. Wir bieten Ihnen eine Fülle an Obst und Gemüse, die Ihre Sinne erfreuen wird. Von knackigen Karotten bis hin zu saftigen Beeren und von bunten Paprika bis hin zu vitaminreichen Orangen – wir haben alles, was Ihr kulinarisches Herz begehrt.</p>
    <img src="/images/ho2.png" class="main-image">
    <p class="main-paragraph">Besuchen Sie unsere Webseite, um mehr über unsere Produkte und unsere Leidenschaft für frische Erzeugnisse zu erfahren. "Kraut & Rüben" ist mehr als nur ein regionaler Betrieb – wir sind Ihre Partner, wenn es darum geht, köstliche, gesunde und nachhaltige Lebensmittel zu genießen. Gemeinsam machen wir die Welt ein bisschen grüner und bunter.</p>
    <p class="main-paragraph">Lassen Sie sich von uns inspirieren und tauchen Sie ein in die wunderbare Welt von "Kraut & Rüben" – Ihrem Zuhause für erstklassige Produkte aus der Natur.</p>
</div>